// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewParent struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
}

type NewStudent struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
	ParentID   string `json:"parentId"`
}

type NewTeacher struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
}

type NewUnitAdmin struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
}

type ParentHTTP struct {
	UserHTTP *UserHTTP      `json:"userHttp"`
	Children []*StudentHTTP `json:"children"`
}

type StudentHTTP struct {
	UserHTTP     *UserHTTP `json:"userHttp"`
	RobboGroupID string    `json:"robboGroupId"`
	RobboUnitID  string    `json:"robboUnitId"`
}

type SuperAdminHTTP struct {
	UserHTTP *UserHTTP `json:"userHttp"`
}

type TeacherHTTP struct {
	UserHTTP *UserHTTP `json:"userHttp"`
}

type UnitAdminHTTP struct {
	UserHTTP *UserHTTP `json:"userHttp"`
}

type UpdateParentHTTP struct {
	UserHTTP *UpdateUserHTTP `json:"userHttp"`
}

type UpdateParentInput struct {
	ParentHTTP *UpdateParentHTTP `json:"parentHttp"`
}

type UpdateStudentHTTP struct {
	UserHTTP *UpdateUserHTTP `json:"userHttp"`
}

type UpdateStudentInput struct {
	StudentHTTP *UpdateStudentHTTP `json:"studentHttp"`
}

type UpdateSuperAdminHTTP struct {
	UserHTTP *UpdateUserHTTP `json:"userHttp"`
}

type UpdateSuperAdminInput struct {
	SuperAdminHTTP *UpdateSuperAdminHTTP `json:"superAdminHttp"`
}

type UpdateTeacherHTTP struct {
	UserHTTP *UpdateUserHTTP `json:"userHttp"`
}

type UpdateTeacherInput struct {
	TeacherHTTP *UpdateTeacherHTTP `json:"teacherHttp"`
}

type UpdateUnitAdminHTTP struct {
	UserHTTP *UpdateUserHTTP `json:"userHttp"`
}

type UpdateUnitAdminInput struct {
	UnitAdminHTTP *UpdateUnitAdminHTTP `json:"unitAdminHttp"`
}

type UpdateUserHTTP struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
}

type UserHTTP struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Role       int    `json:"role"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
	CreatedAt  string `json:"createdAt"`
}
