// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewParent struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
}

type NewStudent struct {
	Email        string `json:"email"`
	Password     string `json:"password"`
	Nickname     string `json:"nickname"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Middlename   string `json:"middlename"`
	RobboGroupID string `json:"robboGroupId"`
	RobboUnitID  string `json:"robboUnitId"`
}

type Parent struct {
	User     *User      `json:"user"`
	Children []*Student `json:"children"`
}

type Student struct {
	User         *User  `json:"user"`
	RobboGroupID string `json:"robboGroupId"`
	RobboUnitID  string `json:"robboUnitId"`
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Role       int    `json:"role"`
	Nickname   string `json:"nickname"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Middlename string `json:"middlename"`
	CreatedAt  string `json:"createdAt"`
}
