package courses

import "github.com/skinnykaen/robbo_student_personal_account.git/package/models"

type Gateway interface {
	GetAccessCourseRelationsStudents() (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsTeachers() (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsUnitAdmins() (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsRobboUnits() (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsRobboGroups() (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByStudentId(studentId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByTeacherId(teacherId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByUnitAdminId(unitAdminId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByRobboGroupId(robboGroupId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByRobboUnitId(robboUnitId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelationsByCourseId(courseId string) (courseRelations []*models.CourseRelationCore, err error)
	GetAccessCourseRelations(courseId string, parameter string) (courseRelations []*models.CourseRelationCore, err error)
	DeleteAccessCourseRelationsByStudentId(studentId string) (err error)
	DeleteAccessCourseRelationsByTeacherId(teacherId string) (err error)
	DeleteAccessCourseRelationsByUnitAdminId(unitAdminId string) (err error)
	DeleteAccessCourseRelationsByRobboGroupId(robboGroupId string) (err error)
	DeleteAccessCourseRelationsByRobboUnitId(robboUnitId string) (err error)
	DeleteAccessCourseRelationById(courseRelationId string) (id string, err error)
	CreateAccessCourseRelation(courseRelation *models.CourseRelationCore) (newCourseRelation *models.CourseRelationCore, err error)
	CreateAbsoluteMedia(absoluteMedia *models.AbsoluteMediaCore) (id string, err error)
	CreateMedia(media *models.MediaCore) (id string, err error)
	CreateImage(image *models.ImageCore) (id string, err error)
	CreateCourseApiMediaCollection(courseApiMediaCollection *models.CourseApiMediaCollectionCore) (id string, err error)
	CreateCourse(course *models.CourseCore) (id string, err error)
	DeleteAbsoluteMedia(courseApiMediaCollectionId string) (err error)
	DeleteMedia(courseApiMediaCollectionId string) (err error)
	DeleteImage(courseApiMediaCollectionId string) (err error)
	DeleteCourseApiMediaCollection(courseId string) (id string, err error)
	DeleteCourse(courseId string) (id string, err error)
	UpdateAbsoluteMedia(absoluteMedia *models.AbsoluteMediaCore) (err error)
	UpdateMedia(media *models.MediaCore) (err error)
	UpdateImage(image *models.ImageCore) (err error)
	UpdateCourseApiMediaCollection(courseApiMediaCollection *models.CourseApiMediaCollectionCore) (err error)
	UpdateCourse(course *models.CourseCore) (err error)
}
